package com.rvtechnologies.grigora.utils

object ApiConstants {
    const val BASE_URL = "http://3.13.78.53/api/"
    const val SOCKET_URL = "http://3.13.78.53:3000/"

    const val CHANGE_LANGUAGE_URL = "change-language"
    const val LOGIN_URL = "login"
    const val PHONE_LOGIN_URL = "phone-login"
    const val SIGNUP_URL = "signup"
    const val SOCIAL_LOGIN_URL = "social-login"
    const val PROMO_RESTAURANTS = "promo-restaurants"

    const val FORGOT_PASSWORD_URL = "forgot-password"

    const val GET_ALL_CATEGORIES_URL = "get-all-categories"
    const val GET_CUISINE_URL = "get-cuisine"
    const val GET_RESTAURANTS_URL = "restaurant-list"
    const val GET_POPULAR_RESTAURANT_URL = "popular-restaurants"
    const val SEARCH_RESTAURANTS = "search"
    const val GET_RESTAURANTS_BY_CUISINE_URL = "get-restaurant-by-cuisine"

    const val GET_RESTAURANTS_BY_SEARCH_URL = "search"

    const val GET_MENU_ITEM_BY_CATEGORY_URL = "get-items-by-category"
    const val GET_RESTAURANTS_DETAILS = "restaurant-details"
    const val GET_OFFER_LIST_URL = "restaurant-promo"

    const val GET_ORDER_DETAILS_URL = "order-details"

    const val PROFILE_DETAILS_URL = "get-userinfo"
    const val GET_PURCHASED_CARDS = "my-purchased-card"

    const val ADD_ITEM_URL = "add-cart"
    const val ADD_GROUP_ITEM_CART = "add-in-group-cart"
    const val CHANGE_ORDER_TYPE = "change-ordertype"
    const val UPDATE_CART_QTY = "update-cart-item-quantity"
    const val REMOVE_CART_URL = "remove-cart"
    const val CART_ITEMS_URL = "cart-item-list"
    const val GROUP_CART_ITEMS_URL = "group-cart-item-list"

    const val PAY_STACK = "pay-stack"
    const val VIEW_GROUP_CART_URL = "view-group-cart"
    const val VIEW_CART_URL = "view-cart"

    const val PLACE_ORDER_URL = "place-order"
    const val SCHEDULE_ORDER_URL = "schedule-order"

    const val LOCATION_TYPES_URL = "location-types"
    const val GET_CURRENT_ORDERS_URL = "customer-ongoing-order"
    const val GET_PAST_ORDERS_URL = "customer-past-order"
    const val GET_UPCOMING_ORDERS_URL = "customer-upcoming-order"
    const val ADD_RATING_REVIEW_URL = "add-rating-review"
    const val ADD_RATING_REVIEW_URL_MEALS = "add-items-rating"
    const val LIKE_UNLIKE_URL = "favourite"

    const val EDIT_PROFILE_URL = "edit-profile"
    const val CHANGE_PASSWORD_URL = "change-password"

    const val RESTAURANT_REVIEW_URL = "restaurant-reviews"
    const val UPDATE_FIREABSE_TOKEN = "update-user-token"
    const val CANCEL_ORDER = "cancel-order"
    const val COMPLETE_PICKUP_ORDER = "complete-pickup-order"
    const val TABLE_BOOKING_LIST = "table-booking-list"
    const val LOGOUT = "logout"
    const val CONTACT_US = "contact-us"
    const val CHANGE_ANONOMOUS_TO_LOGIN = "change-anonymous-to-login"

    const val SEARCH_USER = "search-customer"
    const val GET_VOUCHER_CODES = "get-voucher-codes"
    const val SEND_GIFT = "send-gift-card"
    const val GET_ALL_CARTS = "check-login-logout-cart"
    const val BUY_CARD = "buy-card"
    const val GET_VOUCHER_CARD = "voucher-card"
    const val MY_CARDS = "my-gift-card"
    const val TRANSFER_MONEY = "send-wallet-money"
    const val REDEEM_CODE = "redeme-card"
    const val WALLET_HISTORY = "wallet-history"
    const val ADD_MONEY = "wallet-in"
    const val GET_ALL_ADDRESSES = "get-user-addresses"
    const val ADD_ADDRESS = "add-user-location"
    const val DASHBOARD_DATA = "customer-home-screen"
    const val BOOK_TABLE = "book-table"
    const val QUIZ_QUESTION = "quiz-question"
    const val QUIZ_ANSWER = "check-quiz-answer"
    const val NOTIFICATIONS_LIST = "notification-list"
    const val PICKUP_RESTAURANTS = "pickup-restaurants"
    const val CHANGE_DELIVERY_TO_PICKUP = "change-delievry-to-pickup"
    const val CREATE_GROUP_CART = "create-group-cart"
    const val GET_GROUP_ORDERS = "get-group-carts"
    const val GET_CHT_HEADS = "chatheads"
    const val SAVE_CART_LINK = "save-cart-link"
    const val ADD_IN_GROUP_CART = "add-in-group-cart"
    const val SHOW_ALL_FILTER_DATA = "show-all-filter-data"
    const val RE_ORDER = "re-order"
    const val DELETE_NOTIFICATION = "delete-notification"
    const val FAQ = "faqs"
    const val GET_SUB_ISSUES = "get-sub-issues"
    const val GET_CHAT = "getchat"
    const val SEND_MESSGAE = "chat"
    const val TRENDING_MEALS = "trending-items"
}